name: Test
on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  code-formatting:
    name: Code Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
      - run: cargo fmt --check

  code-linter:
    name: Code Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Run cargo clippy
        run: |
          rustup component add clippy
          cargo clippy --all-features --all-targets --workspace

  tests:
    name: Tests
    runs-on: runs-on=${{ github.run_id }}/family=c6a.8xlarge/image=ubuntu24-full-x64/disk=large/extras=s3-cache
    container: rust:latest
    steps:
      - name: Setup RunsOn
        uses: runs-on/action@v2
        with:
          metrics: cpu,network,memory,disk,io
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y libudev-dev libclang-dev protobuf-compiler
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
      - name: Install cargo-near CLI and cargo-nextest
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/cargo-near/releases/download/cargo-near-v0.20.0/cargo-near-installer.sh | sh
          curl -LsSf https://get.nexte.st/0.9/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
      - name: Run tests
        run: cargo nextest run --test-threads 10 --no-fail-fast
